version: '3'

volumes:
  lifestores_assessment_local_postgres_data: {}
  lifestores_assessment_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: lifestores_assessment_local_django
    container_name: lifestores_assessment_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lifestores_assessment_production_postgres
    container_name: lifestores_assessment_local_postgres
    volumes:
      - lifestores_assessment_local_postgres_data:/var/lib/postgresql/data:Z
      - lifestores_assessment_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
      - ./.env
